config/routes.rb
Rails.application.routes.draw do
  devise_for :users #userGemで自動生成ユーザー機能に必要な複数のルーティングを一度に生成してくれるdeviseのメソッド
  root to: 'tweets#index' #ホーム画面を表示するための記述ルートパス
  resources :tweets do#7つのアクションの集合
    resources :comments, only: :create#今回は「コメントを投稿する」機能、つまり「コメント情報を作る機能」を実装するのでcreateアクションのルーティングとします。
    collection do
      get 'search'#collectionとmemberがある
    end
  end#どのツイートに対するコメントなのかをパスから判断できるようにしたいので、ここではルーティングのネストという方法を使っていきます。
  resources :users, only: :show
end
# ////////////////////////////////

# root   "posts#index"
# post   "posts"          => "posts#create"
# get    "posts/new"      => "posts#new"
# get    "posts/:id/edit" => "posts#edit"
# get    "posts/:id"      => "posts#show"
# patch  "posts/:id"      => "posts#update"
# delete "posts/:id"      => "posts#destroy"

# ////////////////////////////////

# get    "users"          => "users#index"
# post   "users"          => "users#create"
# get    "users/new"      => "users#new"
# get    "users/:id/edit" => "users#edit"
# get    "users/:id"      => "users#show"
# patch  "users/:id"      => "users#update"
# delete "users/:id"      => "users#destroy"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :tweet  # tweetsテーブルとのアソシエーション
  belongs_to :user  # usersテーブルとのアソシエーション
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	validates :text, presence: true #validates :カラム名, バリデーションの種類
	belongs_to :user #validates :user_id presence: true ←不要
	has_many :comments  # commentsテーブルとのアソシエーション

	# def self.search(search)
  #   if search != ""
  #     Tweet.where('text LIKE(?)', "%#{search}%")
  #   else
  #     Tweet.all
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :comments  # commentsテーブルとのアソシエーション
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    comment = Comment.create(commentparams)
    redirect_to "/tweets/#{comment.tweet.id}"# コメントと結びつくツイートの詳細画面に遷移する
		#URIが/tweets/:tweet_id/comments(.:format)
		#:tweet_idの箇所へ、コメントと結びつくツイートのidを記述すると、paramsのなかにtweet_idというキーでパラメーターが追加され、コントローラーで扱うことができます。
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]#exceptエクセプトオプションexceptは「除外する」という意味があります。こちらの後に指定したアクションに対しては、事前処理は実行されません。
  #before_actionによりmove_to_indexメソッドが先に実行され、indexアクションのindex.html.erbページにリダイレクトしてくれます

	def index
    # @tweets = Tweet.all
    # @tweets = Tweet.includes(:user) #モデル名.includes(:紐付くモデル名)includesメソッドを使用してN+1問題を解消します。ちなみに、includesメソッドを使用するとすべてのレコードを取得するため、allメソッドは省略可能です。
    @tweets = Tweet.includes(:user).order("created_at DESC")#	インスタンス = モデル名.order("並び替えの基準となるカラム名 並び順")
    #render json: @tweets #
  end

  def new #CRUDのC（CREATE）インスタンスの生成
    @tweet = Tweet.new
  end

  def create #CRUDのC（CREATE）
    Tweet.create(tweet_params)
  end

  def destroy #CRUDのD（DELETE）
    tweet = Tweet.find(params[:id]) 
    tweet.destroy
  end

  def edit #CRUDのU（UPDATE）
    # @tweet = Tweet.find(params[:id])#set_tweetへ
  end

  def update #CRUDのU（UPDATE）
    tweet = Tweet.find(params[:id]) #なんでfindなんだろう？
    tweet.update(tweet_params)
  end

  def show
    # @tweet = Tweet.find(params[:id])#set_tweetへ
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)#モデル名.includes(:紐付くモデル名)
  end

  # def search
  #   @tweets = Tweet.search(params[:keyword])
  # end

  def search
    @tweets = SearchTweetsService.search(params[:keyword])
  end

  private
  def tweet_params
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)#params.require(:モデル名).permit(:キー名, :キー名),current_userメソッド
    #requireメソッドは送信されたパラメーターの情報を持つparamsが、使用できるメソッドparamsが使用できるメソッドです。
    #permitメソッドを使用すると、取得したいキーを指定でき、指定したキーと値のセットのみを取得します
    #margeメソッド ハッシュを結合させるときに使用するRubyのメソッド
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index 
    unless user_signed_in?# unless 条件式 ユーザーがログインしていない場合indexに戻るメソッド
      redirect_to action: :index #redirect_to action: :リダイレクト先となるアクション名
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
    user = User.find(params[:id])#これを入れることでデータベースからuserを取ってきてくれる
    @nickname = user.nickname
    @tweets = user.tweets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper #モジュールとは、Rubyにおける「インスタンスを生成できないクラス」Helperとは、ヘルパーメソッドを作成できるモジュール
  def tweet_lists(tweets)
    html = ''
    tweets.each do |tweet|
      html += render(partial: 'tweet',locals: { tweet: tweet })
    end
    return raw(html)
  end
end

# <% @tweets.each do |tweet| %>
	# <% render partial: "tweet", locals: { tweet: tweet } %>
# <% end %>

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictweet2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">PicTweet</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6"> 
          <%# <div class="user_nav grid-6"> %>
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
            <%= link_to "投稿する", new_tweet_path, class: "post" %>
            <%# <a class="post" href="/tweets/new">投稿する</a> %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
          <%# </div> %> 
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright PicTweet 2019.
      </p>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %><%#@を消しているrenderの先は@を消したほうが望ましいため %>
	<%= form.text_field :image, placeholder: "Image Url" %>
	<%= form.text_area :text, placeholder: "text", rows: "10" %>
	<%= form.submit "SEND" %>
<% end %>

app/views/tweets/_tweet.html.erb
    <div class="content_post" style="background-image: url(<%= tweet.image %>);">
          <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', tweet_path(tweet.id), method: :get %>
          </li>
          <% if user_signed_in? && current_user.id == tweet.user_id %><%#カレントユーザー以外は見れない設定 %>
            <li>
              <%= link_to '編集', edit_tweet_path(tweet.id), method: :get %>
            </li>
            <li>
              <%= link_to '削除', tweet_path(tweet.id), method: :delete %> <%#  Prefixなので、tweet_pathとパスを指定 /tweets/#{tweet.id}でもよい、このとき、HTTPメソッドがDELETEであることにも注意 %>
            </li>
          <% end %><%#カレントユーザー以外は見れない設定 %>
        </ul>
      </div>
      <p><%= tweet.text %></p>
      <span class="name">
        <%# <%= tweet.name %> 
          <a href="/users/<%= tweet.user.id %>">
        <%# <a href=""> %>
          <span>投稿者</span><%= tweet.user.nickname %>
        </a>
      </span>
    </div>

app/views/tweets/create.html.erb
<div class="contents row">
	<div class="success">
		<h3>投稿が完了しました。</h3> 
		<a class="btn" href="/">投稿一覧へ戻る</a> 
	</div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= render partial: "form", locals: { tweet: @tweet } %>
  </div>
</div>

app/views/tweets/index.html.erb
<%# 検索フォーム %>
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<div class="contents row">
  <%# @tweets.each do |tweet| %>
    <%#= render partial: "tweet", locals: { tweet: tweet } %><%# <% render partial: "sample" _sample.html.erbという部分テンプレートを呼び出しています%>
  <%# <% render partial: "sample", locals: { post: "hello!" } localsというオプションを付けることで、部分テンプレート内でその変数を使えるようになります%>
  <%# end %>
   <%= tweet_lists(@tweets) %><%# ヘルパーメソッドをしようしたレンダー %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= render partial: "form", locals: { tweet: @tweet } %>
  </div>
</div>

app/views/tweets/search.html.erb
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
    <% if user_signed_in? && current_user.id == @tweet.user_id %><%#「ユーザーがログインしている」かつ「投稿したユーザーである投稿だけに許可」という実装%>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '編集', edit_tweet_path(@tweet.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', tweet_path(@tweet.id), method: :delete %>
          </li>
        </ul>
      </div>
    <% end %><%#「ユーザーがログインしている」かつ「投稿したユーザーである投稿だけに許可」という実装%>

    <p><%= @tweet.text %></p>
    <%# <span class="name"><%= @tweet.name %> 
        <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
    </div>
    <%#ここから↓コメント入力フォーム %>
  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
      <%#ここから↓コメント %>
        <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%# link_toのとなりが表示名、右がリンクなのでroutesを確認してidを取得するならモデルを確認 %>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @tweets.each do |tweet| %>
    <%# <div class="content_post" style="background-image: url(<%= tweet.image %>
      <%# <p><%= tweet.text %>
    <%# </div> %>
        <%= render partial: "tweets/tweet", locals: { tweet: tweet } %><%# eachを外で使っていてそのままのtweetでは中では通用しない為 %>
  <% end %>
</div>